default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>
  timeout: 5000
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] || 'messaging-app' %>
test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] || 'messaging-app-test' %>

production:
  <<: *default
